<?php

namespace Database\Seeders\SystemManagements;

use App\Enums\Gender;
use App\Features\SystemManagements\Models\Role;
use App\Features\SystemManagements\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TestSeederUsers extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create Ministry role
        $ministryRole = Role::firstOrCreate(
            ['name' => 'ministry'],
            ['caption' => 'Ministry']
        );

        // Create Ministry user
        $ministryUser = User::create([
            'name' => 'Ministry User',
            'email' => 'ministry@example.com',
            'role_id' => $ministryRole->id,
            'password' => Hash::make('password'),
            'email_verified_at' => now(),
        ]);

        $ministryUser->userInformation()->create([
            'phone_code' => '+20',
            'phone_number' => '1000000001',
            'date_of_birth' => '1985-01-01',
            'gender' => Gender::MALE,
            'nationality' => 'Egyptian',
            'address' => 'Ministry of Education, Cairo',
            'city' => 'Cairo',
            'state' => 'Cairo',
            'country' => 'Egypt',
            'bio' => 'Ministry of Education representative',
        ]);

        // Create all test students
        $students = [
            [
                'name' => 'عمر ياسر صالح',
                'email' => 'student70571@student.com',
                'phone_code' => '966',
                'phone_number' => '539674413',
                'date_of_birth' => '2016-06-01',
                'gender' => Gender::MALE,
                'grade_id' => 4,
                'nationality' => 'Saudi',
                'address' => 'حي الورود، مدينة الرياض، منطقة الرياض، الرمز البريدي 11564، المملكة العربية السعودية.',
                'city' => 'الرياض',
                'state' => 'حى الورود',
                'country' => 'المملكة العربية السعودية',
                'emergency_contact_name' => 'ياسر صالح',
                'emergency_contact_phone' => '966654000000',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'مصطفي أسامه مصطفي',
                'email' => 'student10696@student.com',
                'phone_code' => '20',
                'phone_number' => '1068782134',
                'date_of_birth' => '2016-09-25',
                'gender' => Gender::MALE,
                'grade_id' => 4,
                'nationality' => 'Egyptian',
                'address' => '١٢ شارع النيل، حي الزمالك، محافظة القاهرة، جمهورية مصر العربية',
                'city' => 'القاهرة',
                'state' => 'الزمالك',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'اسامة مصطفى',
                'emergency_contact_phone' => '1068782134',
                'bio' => 'Grade 4 student',
            ],
            [
                'name' => 'Omar Mohamed El-Moshad',
                'email' => 'student72667@student.com',
                'phone_code' => '20',
                'phone_number' => '1011420250',
                'date_of_birth' => '2016-10-16',
                'gender' => Gender::MALE,
                'grade_id' => 4,
                'nationality' => 'Egyptian',
                'address' => '٤٨ شارع بورسعيد، حي الدقي، محافظة الجيزة، جمهورية مصر العربية',
                'city' => 'الجيزة',
                'state' => 'الدقى',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohamed El-Moshad',
                'emergency_contact_phone' => '1011420250',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'Ali Mohamed Yehia',
                'email' => 'student72668@student.com',
                'phone_code' => '20',
                'phone_number' => '1006636306',
                'date_of_birth' => '2016-07-23',
                'gender' => Gender::MALE,
                'grade_id' => 4,
                'nationality' => 'Egyptian',
                'address' => '١ شارع النيل، حي أسوان، محافظة أسوان، جمهورية مصر العربية',
                'city' => 'أسوان',
                'state' => 'أسوان',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohamed Yehia',
                'emergency_contact_phone' => '1006636306',
                'bio' => 'Grade 4 student',
            ],
            [
                'name' => 'Hoor Farag',
                'email' => 'student13618@student.com',
                'phone_code' => '971',
                'phone_number' => '502868380',
                'date_of_birth' => '2016-08-12',
                'gender' => Gender::FEMALE,
                'grade_id' => 4,
                'nationality' => 'Emirati',
                'address' => 'Al Nahda Street, Near Al Nahda Park, Residential Building',
                'city' => 'Dubai',
                'state' => 'Dubai',
                'country' => 'United Arab Emirates',
                'emergency_contact_name' => 'Farag',
                'emergency_contact_phone' => '971503000000',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'Asia Mohamed Ali Ghanem',
                'email' => 'student72653@student.com',
                'phone_code' => '20',
                'phone_number' => '1040400322',
                'date_of_birth' => '2016-07-16',
                'gender' => Gender::FEMALE,
                'grade_id' => 4,
                'nationality' => 'Egyptian',
                'address' => '١٠ شارع الملك فيصل، حي طنطا، محافظة الغربية، جمهورية مصر العربية',
                'city' => 'الغربية',
                'state' => 'طنطا',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohamed Ali Ghanem',
                'emergency_contact_phone' => '1040400322',
                'bio' => 'Student enrolled in online courses',
            ],
            [
                'name' => 'Fatma Baha Fathy Al Halbouni',
                'email' => 'student51868@student.com',
                'phone_code' => '965',
                'phone_number' => '65799533',
                'date_of_birth' => '2016-11-29',
                'gender' => Gender::FEMALE,
                'grade_id' => 4,
                'nationality' => 'Kuwaiti',
                'address' => '12، شارع 5، منطقة الرّي، مدينة الكويت، محافظة العاصمة، الكويت',
                'city' => 'العاصمة',
                'state' => 'منطقة الرى',
                'country' => 'الكويت',
                'emergency_contact_name' => 'Fathy Al Halbouni',
                'emergency_contact_phone' => '96565799533',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'Anas Ahmed Obeid',
                'email' => 'student51870@student.com',
                'phone_code' => '971',
                'phone_number' => '552593056',
                'date_of_birth' => '2016-07-16',
                'gender' => Gender::MALE,
                'grade_id' => 4,
                'nationality' => 'Emirati',
                'address' => 'Khalifa City, Zone 12, Villa Area',
                'city' => 'Abu Dhabi',
                'state' => 'Abu Dhabi',
                'country' => 'United Arab Emirates',
                'emergency_contact_name' => 'Ahmed Obeid',
                'emergency_contact_phone' => '971553000000',
                'bio' => 'Grade 4 student',
            ],
            [
                'name' => 'دانه حسن مصطفى',
                'email' => 'student10764@student.com',
                'phone_code' => '974',
                'phone_number' => '50218819',
                'date_of_birth' => '2016-11-06',
                'gender' => Gender::FEMALE,
                'grade_id' => 4,
                'nationality' => 'Qatari',
                'address' => '123 شارع الريان، منطقة السد، الدوحة، قطر، 12345',
                'city' => 'الدوحة',
                'state' => 'منطقة السد',
                'country' => 'قطر',
                'emergency_contact_name' => 'حسن مصطفى',
                'emergency_contact_phone' => '97450218819',
                'bio' => 'Student enrolled in online courses',
            ],
            [
                'name' => 'Ziad Hassan Abu Eita',
                'email' => 'student72643@student.com',
                'phone_code' => '20',
                'phone_number' => '1202258469',
                'date_of_birth' => '2015-10-16',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Egyptian',
                'address' => '٣٠ شارع التحرير، حي الأقصر، محافظة الأقصر، جمهورية مصر العربية',
                'city' => 'الاقصر',
                'state' => 'الاقصر',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Hassan Abu Eita',
                'emergency_contact_phone' => '1202258469',
                'bio' => 'Grade 5 student',
            ],
            [
                'name' => 'Mohammed Mohammed Abu Al-Nasr',
                'email' => 'student72637@student.com',
                'phone_code' => '20',
                'phone_number' => '1060113116',
                'date_of_birth' => '2015-04-17',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Egyptian',
                'address' => '٢٢ شارع البحر، حي شرم الشيخ، محافظة جنوب سيناء، جمهورية مصر العربية',
                'city' => 'جنوب سيناء',
                'state' => 'شرم الشيخ',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohammed Abu Al-Nasr',
                'emergency_contact_phone' => '1060113116',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'Sufyan Abdelhamid Hassan',
                'email' => 'student50509@student.com',
                'phone_code' => '966',
                'phone_number' => '546384200',
                'date_of_birth' => '2015-06-20',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Saudi',
                'address' => 'منزل رقم 102، حي النسيم، مدينة جدة، منطقة مكة المكرمة، الرمز البريدي 21442، المملكة العربية السعودية.',
                'city' => 'مكة المكرمة',
                'state' => 'جدة',
                'country' => 'المملكة العربية السعودية',
                'emergency_contact_name' => 'Abdelhamid Hassan',
                'emergency_contact_phone' => '966546000000',
                'bio' => 'Student enrolled in online courses',
            ],
            [
                'name' => 'Omar Mohammed Sadiq',
                'email' => 'student70600@student.com',
                'phone_code' => '20',
                'phone_number' => '1281203726',
                'date_of_birth' => '2015-01-22',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Egyptian',
                'address' => 'كورنيش النيل، رشدي، الإسكندرية، مصر، 21532',
                'city' => 'الاسكندرية',
                'state' => 'رشدى',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohammed Sadiq',
                'emergency_contact_phone' => '1281203726',
                'bio' => 'A curious student who loves learning new things every day.',
            ],
            [
                'name' => 'Yousef Mohammed Al-Salamouni',
                'email' => 'student51854@student.com',
                'phone_code' => '965',
                'phone_number' => '60962279',
                'date_of_birth' => '2015-08-26',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Kuwaiti',
                'address' => 'بناية النور، شارع الجهراء، محافظة الجهراء، الكويت',
                'city' => 'الجهراء',
                'state' => 'الجهراء',
                'country' => 'الكويت',
                'emergency_contact_name' => 'Mohammed Al-Salamouni',
                'emergency_contact_phone' => '96560962279',
                'bio' => 'Loves solving puzzles and challenging tasks.',
            ],
            [
                'name' => 'يحيي على ابو العلا على',
                'email' => 'student13604@student.com',
                'phone_code' => '20',
                'phone_number' => '1554362890',
                'date_of_birth' => '2015-12-16',
                'gender' => Gender::MALE,
                'grade_id' => 5,
                'nationality' => 'Egyptian',
                'address' => 'شارع شبين الكوم، شبين الكوم، المنوفية، مصر، 32911',
                'city' => 'المنوفية',
                'state' => 'شبين الكوم',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'على ابو العلا على',
                'emergency_contact_phone' => '1554362890',
                'bio' => 'A motivated student aiming to improve skills every day.',
            ],
            [
                'name' => 'نور الدين احمد نور الدين',
                'email' => 'student12923@student.com',
                'phone_code' => '20',
                'phone_number' => '1159794203',
                'date_of_birth' => '2014-01-14',
                'gender' => Gender::MALE,
                'grade_id' => 6,
                'nationality' => 'Egyptian',
                'address' => 'طريق الهرم، الهرم، الجيزة، مصر، 12556',
                'city' => 'الجيزة',
                'state' => 'الهرم',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'احمد نور الدين',
                'emergency_contact_phone' => '1159794203',
                'bio' => 'Primary stage student',
            ],
            [
                'name' => 'Mohammed Ahmed Khaled',
                'email' => 'student51851@student.com',
                'phone_code' => '966',
                'phone_number' => '542190911',
                'date_of_birth' => '2014-03-21',
                'gender' => Gender::MALE,
                'grade_id' => 6,
                'nationality' => 'Saudi',
                'address' => 'عمارة الريان، شارع الأمير متعب، الطائف، منطقة مكة المكرمة، السعودية',
                'city' => 'مكة المكرمة',
                'state' => 'الطائف',
                'country' => 'المملكة العربية السعودية',
                'emergency_contact_name' => 'Ahmed Khaled',
                'emergency_contact_phone' => '966542000000',
                'bio' => 'Grade 6 student',
            ],
            [
                'name' => 'Malak Mohamed Ashraf',
                'email' => 'student13595@student.com',
                'phone_code' => '20',
                'phone_number' => '1002989286',
                'date_of_birth' => '2014-05-19',
                'gender' => Gender::FEMALE,
                'grade_id' => 6,
                'nationality' => 'Egyptian',
                'address' => '45 شارع الجمهورية، حي شرق، قنا، محافظة قنا، مصر',
                'city' => 'قنا',
                'state' => 'حي شرق',
                'country' => 'جمهورية مصر العربية',
                'emergency_contact_name' => 'Mohamed Ashraf',
                'emergency_contact_phone' => '1002989286',
                'bio' => 'Student enrolled in online courses',
            ],
            [
                'name' => 'Sandy Abo El-Ez',
                'email' => 'student51833@student.com',
                'phone_code' => '966',
                'phone_number' => '543081023',
                'date_of_birth' => '2014-09-20',
                'gender' => Gender::FEMALE,
                'grade_id' => 6,
                'nationality' => 'Saudi',
                'address' => '77 شارع الملك عبدالله، حي النسيم، بريدة، منطقة القصيم، السعودية',
                'city' => 'القصيم',
                'state' => 'حي النسيم',
                'country' => 'المملكة العربية السعودية',
                'emergency_contact_name' => 'Abo El-Ez',
                'emergency_contact_phone' => '966543000000',
                'bio' => 'Enthusiastic about reading and exploring the world around me.',
            ],
        ];

        foreach ($students as $studentData) {
            $student = User::create([
                'name' => $studentData['name'],
                'email' => $studentData['email'],
                'role_id' => 2, // student role
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]);

            $student->userInformation()->create([
                'phone_code' => $studentData['phone_code'],
                'phone_number' => $studentData['phone_number'],
                'date_of_birth' => $studentData['date_of_birth'],
                'gender' => $studentData['gender'],
                'grade_id' => $studentData['grade_id'],
                'nationality' => $studentData['nationality'],
                'address' => $studentData['address'],
                'city' => $studentData['city'],
                'state' => $studentData['state'],
                'country' => $studentData['country'],
                'emergency_contact_name' => $studentData['emergency_contact_name'],
                'emergency_contact_phone' => $studentData['emergency_contact_phone'],
                'bio' => $studentData['bio'],
            ]);
        }

        // Create 5 test teacher users
        $teachers = [
            [
                'name' => 'Ahmed Mohamed',
                'email' => 'teacher1@example.com',
                'phone_number' => '1112223331',
                'gender' => Gender::MALE,
                'bio' => 'Mathematics Teacher with 10 years experience',
            ],
            [
                'name' => 'Fatma Ali',
                'email' => 'teacher2@example.com',
                'phone_number' => '1112223332',
                'gender' => Gender::FEMALE,
                'bio' => 'Science Teacher specializing in Physics',
            ],
            [
                'name' => 'Mohamed Hassan',
                'email' => 'teacher3@example.com',
                'phone_number' => '1112223333',
                'gender' => Gender::MALE,
                'bio' => 'Arabic Language Teacher',
            ],
            [
                'name' => 'Sara Ibrahim',
                'email' => 'teacher4@example.com',
                'phone_number' => '1112223334',
                'gender' => Gender::FEMALE,
                'bio' => 'English Language Teacher',
            ],
            [
                'name' => 'Omar Khaled',
                'email' => 'teacher5@example.com',
                'phone_number' => '1112223335',
                'gender' => Gender::MALE,
                'bio' => 'History and Geography Teacher',
            ],
        ];

        foreach ($teachers as $index => $teacherData) {
            $teacher = User::create([
                'name' => $teacherData['name'],
                'email' => $teacherData['email'],
                'role_id' => 3, // teacher role
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]);

            $teacher->userInformation()->create([
                'phone_code' => '+20',
                'phone_number' => $teacherData['phone_number'],
                'date_of_birth' => fake()->dateTimeBetween('-50 years', '-25 years')->format('Y-m-d'),
                'gender' => $teacherData['gender'],
                'nationality' => 'Egyptian',
                'address' => fake()->address(),
                'city' => fake()->randomElement(['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan']),
                'state' => 'Egypt',
                'country' => 'Egypt',
                'postal_code' => fake()->postcode(),
                'emergency_contact_name' => fake()->name(),
                'emergency_contact_phone' => fake()->phoneNumber(),
                'bio' => $teacherData['bio'],
            ]);
        }
    }
}


